describe('Ambiente Produccion-Royal Falapgos', () => {
  Cypress.on('uncaught:exception', (err, runnable) => {
    if (err.message.includes("Cannot read properties of undefined (reading 'trim')")) {
      // Manejar el error aquí, por ejemplo, mostrar un mensaje personalizado
      console.log('Se produjo un error al intentar acceder a una propiedad de un objeto indefinido.');
      // Devolver false para evitar que el error se muestre en la consola de Cypress
      return false;
    }
    if (err && err.toString().includes('TypeError')) {
      // Manejar el error aquí, por ejemplo, mostrar un mensaje personalizado
      console.log('Se produjo un error de tipo TypeError.');
      // Devolver false para evitar que el error se muestre en la consola de Cypress
      return false;
    }
  })
  for (let i = 0; i < 30; i++) {
    it('Bookings', () => {
      cy.visit('https://www.royalgalapagos.com/')
      cy.wait(3000)
      cy.get('#sform').click()
      cy.wait(3000)
      cy.get('.search > app-search > .container > .wrap2 > #seachform > form.ng-valid > table > tbody > :nth-child(1) > :nth-child(1) > #seldate').select('August')
      cy.get('.search > app-search > .container > .wrap2 > #seachform > form.ng-valid > table > tbody > :nth-child(1) > #button-space > #btnSearch').click()
      cy.wait(3000)
      cy.get('.search > app-search > .container > .wrap2 > #seachform > form.ng-valid > table > tbody > :nth-child(1) > :nth-child(1) > #seldate').select('September')
      cy.get('.search > app-search > .container > .wrap2 > #seachform > form.ng-valid > table > tbody > :nth-child(1) > #button-space > #btnSearch').click()
      cy.wait(3000)
      cy.get('.search > app-search > .container > .wrap2 > #seachform > form.ng-valid > table > tbody > :nth-child(1) > :nth-child(1) > #seldate').select('October')
      cy.get('.search > app-search > .container > .wrap2 > #seachform > form.ng-valid > table > tbody > :nth-child(1) > #button-space > #btnSearch').click()
      cy.wait(3000)
      cy.get('.search > app-search > .container > .wrap2 > #seachform > form.ng-valid > table > tbody > :nth-child(1) > :nth-child(1) > #seldate').select('November')
      cy.get('.search > app-search > .container > .wrap2 > #seachform > form.ng-valid > table > tbody > :nth-child(1) > #button-space > #btnSearch').click()
      cy.wait(3000)
      cy.get('.search > app-search > .container > .wrap2 > #seachform > form.ng-valid > table > tbody > :nth-child(1) > :nth-child(1) > #seldate').select('December')
      cy.get('.search > app-search > .container > .wrap2 > #seachform > form.ng-valid > table > tbody > :nth-child(1) > #button-space > #btnSearch').click()
      cy.wait(3000)
      cy.get('.search > app-search > .container > .wrap2 > #seachform > form.ng-valid > table > tbody > :nth-child(1) > :nth-child(1) > #selyear').select('2024')
      cy.get('.search > app-search > .container > .wrap2 > #seachform > form.ng-valid > table > tbody > :nth-child(1) > #button-space > #btnSearch').click()
      cy.wait(3000)
      cy.get('.search > app-search > .container > .wrap2 > #seachform > form.ng-valid > table > tbody > :nth-child(1) > :nth-child(1) > #seldate').select('January')
      cy.get('.search > app-search > .container > .wrap2 > #seachform > form.ng-valid > table > tbody > :nth-child(1) > #button-space > #btnSearch').click()
      cy.wait(3000)
      cy.get('.search > app-search > .container > .wrap2 > #seachform > form.ng-valid > table > tbody > :nth-child(1) > :nth-child(1) > #seldate').select('February')
      cy.get('.search > app-search > .container > .wrap2 > #seachform > form.ng-valid > table > tbody > :nth-child(1) > #button-space > #btnSearch').click()
      cy.wait(3000)
      cy.get('.search > app-search > .container > .wrap2 > #seachform > form.ng-valid > table > tbody > :nth-child(1) > :nth-child(1) > #seldate').select('March')
      cy.get('.search > app-search > .container > .wrap2 > #seachform > form.ng-valid > table > tbody > :nth-child(1) > #button-space > #btnSearch').click()
      cy.wait(3000)
      cy.get('.search > app-search > .container > .wrap2 > #seachform > form.ng-valid > table > tbody > :nth-child(1) > :nth-child(1) > #seldate').select('April')
      cy.get('.search > app-search > .container > .wrap2 > #seachform > form.ng-valid > table > tbody > :nth-child(1) > #button-space > #btnSearch').click()
      cy.wait(3000)
      cy.get('.search > app-search > .container > .wrap2 > #seachform > form.ng-valid > table > tbody > :nth-child(1) > :nth-child(1) > #seldate').select('May')
      cy.get('.search > app-search > .container > .wrap2 > #seachform > form.ng-valid > table > tbody > :nth-child(1) > #button-space > #btnSearch').click()
      cy.wait(3000)
      cy.get('.search > app-search > .container > .wrap2 > #seachform > form.ng-valid > table > tbody > :nth-child(1) > :nth-child(1) > #seldate').select('June')
      cy.get('.search > app-search > .container > .wrap2 > #seachform > form.ng-valid > table > tbody > :nth-child(1) > #button-space > #btnSearch').click()
      cy.wait(3000)
      cy.get('.search > app-search > .container > .wrap2 > #seachform > form.ng-valid > table > tbody > :nth-child(1) > :nth-child(1) > #seldate').select('July')
      cy.get('.search > app-search > .container > .wrap2 > #seachform > form.ng-valid > table > tbody > :nth-child(1) > #button-space > #btnSearch').click()
      cy.wait(3000)
      cy.get('.search > app-search > .container > .wrap2 > #seachform > form.ng-valid > table > tbody > :nth-child(1) > :nth-child(1) > #seldate').select('August')
      cy.get('.search > app-search > .container > .wrap2 > #seachform > form.ng-valid > table > tbody > :nth-child(1) > #button-space > #btnSearch').click()
      cy.wait(3000)
      cy.get('.search > app-search > .container > .wrap2 > #seachform > form.ng-valid > table > tbody > :nth-child(1) > :nth-child(1) > #seldate').select('September')
      cy.get('.search > app-search > .container > .wrap2 > #seachform > form.ng-valid > table > tbody > :nth-child(1) > #button-space > #btnSearch').click()
      cy.wait(3000)
      cy.get('.search > app-search > .container > .wrap2 > #seachform > form.ng-valid > table > tbody > :nth-child(1) > :nth-child(1) > #seldate').select('October')
      cy.get('.search > app-search > .container > .wrap2 > #seachform > form.ng-valid > table > tbody > :nth-child(1) > #button-space > #btnSearch').click()
      cy.wait(3000)
      cy.get('.search > app-search > .container > .wrap2 > #seachform > form.ng-valid > table > tbody > :nth-child(1) > :nth-child(1) > #seldate').select('November')
      cy.get('.search > app-search > .container > .wrap2 > #seachform > form.ng-valid > table > tbody > :nth-child(1) > #button-space > #btnSearch').click()
      cy.wait(3000)
      cy.get('.search > app-search > .container > .wrap2 > #seachform > form.ng-valid > table > tbody > :nth-child(1) > :nth-child(1) > #selyear').select('2025')
      cy.get('.search > app-search > .container > .wrap2 > #seachform > form.ng-valid > table > tbody > :nth-child(1) > #button-space > #btnSearch').click()
      cy.wait(3000)
      cy.get('.search > app-search > .container > .wrap2 > #seachform > form.ng-valid > table > tbody > :nth-child(1) > :nth-child(1) > #seldate').select('January')
      cy.get('.search > app-search > .container > .wrap2 > #seachform > form.ng-valid > table > tbody > :nth-child(1) > #button-space > #btnSearch').click()
      cy.wait(3000)
      cy.get('.search > app-search > .container > .wrap2 > #seachform > form.ng-valid > table > tbody > :nth-child(1) > :nth-child(1) > #seldate').select('February')
      cy.get('.search > app-search > .container > .wrap2 > #seachform > form.ng-valid > table > tbody > :nth-child(1) > #button-space > #btnSearch').click()
      cy.wait(3000)
      cy.get('.search > app-search > .container > .wrap2 > #seachform > form.ng-valid > table > tbody > :nth-child(1) > :nth-child(1) > #seldate').select('March')
      cy.get('.search > app-search > .container > .wrap2 > #seachform > form.ng-valid > table > tbody > :nth-child(1) > #button-space > #btnSearch').click()
      cy.wait(3000)
      cy.get('.search > app-search > .container > .wrap2 > #seachform > form.ng-valid > table > tbody > :nth-child(1) > :nth-child(1) > #seldate').select('April')
      cy.get('.search > app-search > .container > .wrap2 > #seachform > form.ng-valid > table > tbody > :nth-child(1) > #button-space > #btnSearch').click()
      cy.wait(3000)
      cy.get('.search > app-search > .container > .wrap2 > #seachform > form.ng-valid > table > tbody > :nth-child(1) > :nth-child(1) > #seldate').select('May')
      cy.get('.search > app-search > .container > .wrap2 > #seachform > form.ng-valid > table > tbody > :nth-child(1) > #button-space > #btnSearch').click()
      cy.wait(3000)
      cy.get('.search > app-search > .container > .wrap2 > #seachform > form.ng-valid > table > tbody > :nth-child(1) > :nth-child(1) > #seldate').select('June')
      cy.get('.search > app-search > .container > .wrap2 > #seachform > form.ng-valid > table > tbody > :nth-child(1) > #button-space > #btnSearch').click()
      cy.wait(3000)
      cy.get('.search > app-search > .container > .wrap2 > #seachform > form.ng-valid > table > tbody > :nth-child(1) > :nth-child(1) > #seldate').select('July')
      cy.get('.search > app-search > .container > .wrap2 > #seachform > form.ng-valid > table > tbody > :nth-child(1) > #button-space > #btnSearch').click()
      cy.wait(3000)
      cy.get('.search > app-search > .container > .wrap2 > #seachform > form.ng-valid > table > tbody > :nth-child(1) > :nth-child(1) > #seldate').select('August')
      cy.get('.search > app-search > .container > .wrap2 > #seachform > form.ng-valid > table > tbody > :nth-child(1) > #button-space > #btnSearch').click()
      cy.wait(3000)
      cy.get('.search > app-search > .container > .wrap2 > #seachform > form.ng-valid > table > tbody > :nth-child(1) > :nth-child(1) > #seldate').select('September')
      cy.get('.search > app-search > .container > .wrap2 > #seachform > form.ng-valid > table > tbody > :nth-child(1) > #button-space > #btnSearch').click()
      cy.wait(3000)
      cy.get('.search > app-search > .container > .wrap2 > #seachform > form.ng-valid > table > tbody > :nth-child(1) > :nth-child(1) > #seldate').select('October')
      cy.get('.search > app-search > .container > .wrap2 > #seachform > form.ng-valid > table > tbody > :nth-child(1) > #button-space > #btnSearch').click()
      cy.wait(3000)
      cy.get('.search > app-search > .container > .wrap2 > #seachform > form.ng-valid > table > tbody > :nth-child(1) > :nth-child(1) > #seldate').select('November')
      cy.get('.search > app-search > .container > .wrap2 > #seachform > form.ng-valid > table > tbody > :nth-child(1) > #button-space > #btnSearch').click()
      cy.wait(3000)
      cy.get('.search > app-search > .container > .wrap2 > #seachform > form.ng-valid > table > tbody > :nth-child(1) > :nth-child(1) > #seldate').select('December')
      cy.get('.search > app-search > .container > .wrap2 > #seachform > form.ng-valid > table > tbody > :nth-child(1) > #button-space > #btnSearch').click()
      cy.wait(3000)
    })
  }
})